[program:nightwatch-agent]
process_name=%(program_name)s
command=php /path/to/your/application/artisan nightwatch:agent
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/nightwatch-agent.log
stopwaitsecs=3600
